image: registry.webstollen.com:443/docker/jtl-plugin-ci:master

stages:
- test
- build
- finalize
- publish

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

composer:
  stage: build
  only:
  - tags
  - master
  cache:
    key:
      files:
      - composer.lock
    paths:
    - vendor
    policy: pull
  script:
  - composer install --no-dev -o
  artifacts:
    expire_in: 3 days
    untracked: true

node:
  stage: build
  only:
  - tags
  - master
  cache:
    key:
      files:
      - adminmenu/app/yarn.lock
    paths:
    - adminmenu/app/node_modules
    - adminmenu/app/.yarn-cache
    policy: pull
  script:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONT_AWESOME_TOKEN
  - npm config set "@dash.bar:registry" https://gitlab.webstollen.com/api/v4/packages/npm/
  - npm config set "@webstollen:registry" https://gitlab.webstollen.com/api/v4/packages/npm/
  - npm config set "//gitlab.webstollen.com/api/v4/packages/npm/:_authToken" $CI_JOB_TOKEN
  - npm config set "//gitlab.webstollen.com/api/v4/projects/444/packages/npm/:_authToken"
    $CI_JOB_TOKEN
  - cd adminmenu/app
  - yarn install --frozen-lockfile --cache-folder .yarn-cache
  - yarn build
  - rm -rf node_modules/
  artifacts:
    expire_in: 3 days
    untracked: false
    paths:
    - adminmenu/app/build

pack:
  stage: finalize
  only:
  - tags
  - master
  script:
  - rm -rf .gitlab-ci.yml .git/ adminmenu/app/src/ adminmenu/app/test/ adminmenu/app/public/
  - rm -f adminmenu/app/*.js* adminmenu/app/yarn.lock adminmenu/app/README.md adminmenu/cra.sh
  - cd ..
  - if [ $SKIP_COMPILE = 1 ]; then echo "Skipped Compiler!"; else compiler $CI_PROJECT_DIR $CI_PROJECT_DIR; fi
  - zip -r $CI_PROJECT_DIR/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip $CI_PROJECT_NAME
  artifacts:
    expire_in: 30 days
    paths:
    - "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip"

upload:
  stage: publish
  only:
  - tags
  - master
  script:
  - aws configure set region eu-central-1
  - aws s3 cp $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip s3://$S3_BUCKET/jtl-plugins/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.zip
